### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aliparlakci** [BlipRanger/bdfr-html#1]
I feel like this project is more of a web project than it is a python script. There are some great static site generators which are really smart about generating HTMLs (Next.js for example). Project could grow a lot quicker if it only focused on providing the archive files to, let's say, Next.js. All the interface design, UI, etc. can be implemented in Next.js. Bottom line, it is a matter of separation of concerns here, in my opinion.

However, if this was meant to be a simple script and will not get any improvements, it looks nice :)

**Comment by BlipRanger** [comment]
> I feel like this project is more of a web project than it is a python script. There are some great static site generators which are really smart about generating HTMLs (Next.js for example). Project could grow a lot quicker if it only focused on providing the archive files to, let's say, Next.js. All the interface design, UI, etc. can be implemented in Next.js. Bottom line, it is a matter of separation of concerns here, in my opinion.
> 
> However, if this was meant to be a simple script and will not get any improvements, it looks nice :)

Sure that makes sense. And I definitely see that as an area for growth, perhaps for a second version. I'll look into some static site generators for sure. For now I will likely try to round out the script into a useful tool that works with V2 well and then consider where to go from there.

**Comment by BlipRanger** [comment]
> > I feel like this project is more of a web project than it is a python script. There are some great static site generators which are really smart about generating HTMLs (Next.js for example). Project could grow a lot quicker if it only focused on providing the archive files to, let's say, Next.js. All the interface design, UI, etc. can be implemented in Next.js. Bottom line, it is a matter of separation of concerns here, in my opinion.
> > However, if this was meant to be a simple script and will not get any improvements, it looks nice :)
> 
> Sure that makes sense. And I definitely see that as an area for growth, perhaps for a second version. I'll look into some static site generators for sure. For now I will likely try to round out the script into a useful tool that works with V2 well and then consider where to go from there.

If you get a chance to try it out, let me know if there are any UX improvements I can make. I'm hoping to add a couple more ways to ensure the archive is complete (grabbing webpages, pulling deleted posts from pushshift) soon. I'm sure there are a bunch of little improvements I can make and will  be working through them (I'm pretty rusty at this sort of project).
